---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-ai-secret
  namespace: kagent
spec:
  encryptedData:
    apiKey: AgCTvdR7GA7GV6KtnizO86OesoFs/uGiTZ0JB34FySTHdCHJ2kIUQFEdrPYaTmA9Dbb0vcnnGhAhHtiZ6APtDtvZGFyV2Ax4fV6RGINYpEpln9QmyXxwJ9Kqmu4z2HqVfIvEhpeh7IjlT6sjAiqrM3yOIwIK2k3wSNV2nS2vXs8ZU3Lyn6kvVhDU/tJQHCg9jjhvFAXwCnQZH56dmUecslDcBUTq1HTXNw7mBdpyGFmgMKT/sdszW7dx2Iq/VQD7+A6RsHtFk2GhxpWlsiKh99b8vqqVhDqa2cWGWLv10Lt5tmrQZbbO6v40SGxE+X7Jhz/osmNNdL15Ov/LmYEB3T8+rsK5ptT6Ljd/Fc4T8lQn/pBLhuV/clAqDbmPX46CcSC0Gy8ibxtw15Zo/UD+IZBlqlqkWR8mIF14pKbHC1InzHqT5+zYThDtg6xhXfiKhYM0fxderk6rb+EqSVCP3egaIW5wcbzLWsUv+fwQ2ctrzWyzfaGpLnVOU7MQqilIEt7IjWdaz08Zv6SLICkNNFmmZTdlVViLNX09ytEH3qxrQV3eRzNQVALdhZT1VEq89wRXa5We0JZzq1XbHvJczpJRRMyoIlthlvlSKGJsKLEVns30+OBBJ4V7dwma4xvQYUyoUcV8ht4GUEMAZ3bYSgqe/H0RfQe0TmZjQqTFjP3AGLQPqmiOCvjkRO0Cj95go4PfYooWUyLLLCpgVDbIfzyuDSwCPrR3eu6dnWR3BNoE0nB2EHPneYngXQhfe5aOZPB0BJwvf4+FG/GSJIdBiCK+gQRmS5acOIdBcajthdGOE8c9eS1gnHFAolJSFBHc0DsIlvctF71kkphke1+/Fdxut+bgU3+bkjKdy/PEkXFrjLVzK6PotjJHoVOO/gmUE3HEDbyYeAh2t2epYW24Eiv/c5yhug==
  template:
    metadata:
      name: open-ai-secret
      namespace: kagent
