---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: kagent
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/helmReleases/kagent/**"
          to: "@artifact/kagent/"
    - name: gateway
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/helmReleases/gateway/**"
          to: "@artifact/gateway"
    - name: cluster
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/helmReleases/cluster/**"
          to: "@artifact/cluster/"
    - name: agentgateway
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/helmReleases/agentgateway/**"
          to: "@artifact/agentgateway/"
    - name: agents
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/helmReleases/agents/**"
          to: "@artifact/agents/"