---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-secret
  namespace: agentgateway-system
spec:
  encryptedData:
    Authorization: AgAWMIg6cZepLpAzKp/1Azqw8hhN2+udqgAT8ROJIlkSm4Od5IKaovqaUTyMAbmLQDXra9OCMT/yBUfOJ7PRAaCdrlch4qODijgSKjL+cvc9yxPKde4FH84rbS2+VJW+QLaUGwEQ9p09kFU5/jY0oc0NyC0tQ16lnGbOdAYyPih8uJ9PtUUt7DWEjgE50B0tKZQyqXeWP7qyiPJsswUHsW6ds2XTGovU2sU1DjCAAITVSVkCjFw9t8b3WdluIWGI+1Qn77D0gySgTHvKtVub+Va6htw7Zea5cVicVZ1g8hBGN6P79Fdi8LaWiMRvvxhPK2jUtHGv0bJh4l604inrgztZZijhUYv2DWkj191MS/+pyZOCZKRmkS8NfIDt+s2ZrCmEeOrJc8pemy8+9cXFhKTET0uVlV9cu9Oy1qdLXBFQixwcEweYICyjFSdgOSuG084zvH9q0OdDsTv4Zo7vDh1gP3CdAgPC7yUf+2lGYXwg/JO1PdeQb1gcd7yryHletl1EGfBc16FGn11OEOjiiJwcF5OzwDZ6UFnMNRyMrIHn00xUE6gMK2UXDuqH/wIAR7CjUQ2WOD74Rj1R0xbnu514yFvwGMAchaTPWI9GDuBaO3h22pTomnOFsg0aVI632QnjpSucKOS7P2+0x3u1+lMxBMrgBIztDGKonKcyQgmAyrwheJAcv6mCOvSh89V6yU2apDedMfDRGKooc2uJnrmS9iR5pGzBtDJXnTTIkZk3Bm9iVweRSfj/AkboQ905Qt6RVGnGOhL++3QsQR2L2N2tczWFvVo0OIuhhm8l5EzLDb3anKLs61CWpfl17ph+As/4zVcwC3jB4M04Uxkg4ana+q55dgKU6LQ15HRMUp2bZV0Iuom9zbYR5fUbg78yMF/v/gmPRIRMzJiargFvQ0sG1FAK2g==
  template:
    metadata:
      name: openai-secret
      namespace: agentgateway-system
