apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: agentgateway-gpt4-mini
  namespace: kagent
spec:
  apiKeySecret: openai-api-key
  apiKeySecretKey: apiKey
  openAI:
    baseUrl: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:80"
    maxTokens: 10000
  model: gpt-4.1-mini