---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kagent-crd
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kagent
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/kagent-dev/kagent/helm/kagent
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crd
  namespace: kagent
spec:
  targetNamespace: kagent
  interval: 5m
  releaseName: kagent
  install:
    createNamespace: true
  chart:
    spec:
      chart: kagent
      version: "0.7"
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
  values:
    providers:
      default: openAI
      providers:
        openAI:
          apiKey:
            secretKeyRef:
              name: openai-api-key
              key: apiKey
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: kagent
spec:
  targetNamespace: kagent
  interval: 5m
  dependsOn:
    - name: kagent-crd
  releaseName: kagent
  install:
    createNamespace: true
  chart:
    spec:
      chart: kagent
      version: "0.7"
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
