---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kagent
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/kagent-dev/kagent/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crd
  namespace: flux-system
spec:
  targetNamespace: kagent
  interval: 5m
  releaseName: kagent-crds
  install:
    createNamespace: true
  chart:
    spec:
      chart: kagent-crds
      version: "0.7"
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: flux-system
spec:
  targetNamespace: kagent
  interval: 5m
  dependsOn:
    - name: kagent-crd
  releaseName: kagent
  install:
    createNamespace: true
  chart:
    spec:
      chart: kagent
      version: "0.7"
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
  values:
    agents:
      k8s-agent:
        enabled: false
      kgateway-agent:
        enabled: false
      istio-agent:
        enabled: false
      promql-agent:
        enabled: false
      observability-agent:
        enabled: false
      argo-rollouts-agent:
        enabled: false
      helm-agent:
        enabled: false
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
    providers:
      default: openAI
      providers:
        openAI:
          apiKeySecretRef: openai-api-key
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-api-key
  namespace: kagent
spec:
  encryptedData:
    apiKey: AgBLvL7ydq0yRWPZNpnvYnMrmyWs85VbE7uyGsONSb9yKNG+Ucxo5NK3TqQBULoosR0brxuNmS2ztiPVXUg8+pldNzmLwp6wk/pweJzt8MB59FOnNeaStPFJF6wVv4A1C7v/B5xA4/8FUHVcvpOZURK20fGBTfM5umWrMIVyBPv16CQFeNRI2LPOMucKvx7V/GF1FWf4aNA8uw9wSHsPLT9hKayWCQQG1X7aVfwEwJlm4hvZqax1zmQpVYmmgh8kNGmMi7Ks2yU5u85hjb7e5eJdcxa1TCJV2aaYi4YlfEV0qMXapHMZUvb8neIOHlVUd2zwAO6T5Wid7u+a6YLUX37nClZ+oBt3hfY3vNnHXK0xVjXp04nNkLFcTCveH3w7yQHXLjohNS/feui/urC66WWzWYm20cdRoD83LsyGWsvOPaXVl47O+cvJjvTrQcjdTLX/148Ba5amE8JCf3nCPLwpPaxLP8qlyedoxPJmtHm6pweEbwSc+4IRASYkfhoavU40u1F4eNk0qhik6a27KBj4Fs9Q+v6z5cBjJIv9Xg39TJbnBcfhxop+QoMk1YuZKFf//Jl5AeDA/Ksdy28js12W3Y58Ys85oqjzg0hoIoKjE3d5rZr/DjCEqNpoY87af+wYqnYaOIBqqq6vMP9nGaAyWlBSjr6P3DNwEvYFu3rg4Dat/9bh7HuDSDCj+LnNJKdGn/qkcNeoIubFMcWh58h6/Dln4yhvIh2MNpDAiczXCURfbLTUNKNmjfD6BzCzsIDj6E2EVgv3/PeLBbMczvJrHS2mSUweHoGVyxdXy3l5i98qUIGj2mcakyxlX7pm2k7xZjaPbmfj2hazRHBuAl4KfrbtLkrJQN66IS8Lvc1mZ6md2W4+r18KIqHL+Xxa/vPnSQJQcdbuoPB4LLcMd3GYUl1j0Q==
  template:
    metadata:
      name: openai-api-key
      namespace: kagent
